// <auto-generated />
using HospitalApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HospitalApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511000002_AddDoctorPostalCode")]
    partial class AddDoctorPostalCode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
