// <auto-generated />
using System;
using HospitalApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HospitalApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507000000_AddPatientDocuments")]
    partial class AddPatientDocuments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
